### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by luiscruz** [tbwuensche/Detecting-Higher-Order-Merge-Conflicts-in-Large-Software-Projects#1]
Hi Thorsten, thank you for such a nice tool. I have a suggestion (not an issue): perhaps, you can list your ICST paper in the README ;) Cheers, Luís

**Comment by luiscruz** [comment]
@tbwuensche

**Comment by tbwuensche** [comment]
Good point, and sorry for the delay. Done.
